import type { NextPage } from 'next'
import Head from 'next/head'
import { FormEvent, useState } from 'react';

import {database} from '../services/firebase';

import styles from '../styles/Home.module.scss';


interface contactDataProps{
  nome: string;
  email: string;
  phone: string;
  observation: string;
}

const Home: NextPage = () => {

  const [nome, setNome] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [phone, setPhone] = useState<string>('');
  const [observation, setObservation ] = useState<string>('');

  function writeDataInDatabase(e: FormEvent):void{
    e.preventDefault();

    const ref = database.ref('contact');

    const contactData:contactDataProps ={
      nome,
      email,
      phone,
      observation
    }

    ref.push(contactData);
    
    setNome('');
    setEmail('');
    setObservation('');
    setPhone('');
  }

  return (
    <>
      <Head>
        <title>PhoneBookk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <form onSubmit={writeDataInDatabase}>
          <input 
            type="text" 
            placeholder='Nome' 
            value={nome}
            onChange={e => setNome(e.target.value)}
          />
          <input 
            type="text" 
            placeholder='email' 
            value={email}
            onChange={e => setEmail(e.target.value)}
          />
          <input 
            type="tel" 
            placeholder='Telefone' 
            value={phone}
            onChange={e => setPhone(e.target.value)}
          />
          <textarea 
            placeholder='Observações' 
            value={observation}
            onChange={e => setObservation(e.target.value)}>

          </textarea>

          <button type='submit'>Salvar</button>
        </form>
        <div className={styles.phoneBox}>
          <input type="text" placeholder='Buscar'/>
          <div className={styles.phoneCard}>
            <div className={styles.topBox}>
              <p className={styles.name}>Fabio dos santos </p>
              <div className={styles.options}>
                <a href="">Editar</a>
                <a href="">Excluir</a>
              </div>
            </div>
            <div className={styles.moreInfo}>
              <p>fabiojunik@gmail.com</p>
              <p>994305673</p>
              <p>Uma pessoa imortal</p>  
            </div>
          </div>
        </div>          
      </main>
  </>
)}

export default Home
