import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>PhoneBookk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <form>
          <input type="text" placeholder='Nome'/>
          <input type="text" placeholder='email'/>
          <input type="tel" placeholder='Telefone'/>
          <textarea placeholder='Observações'></textarea>
          <button type='submit'>Salvar</button>
        </form>
        <div className={styles.phoneBox}>
          <input type="text" placeholder='Buscar'/>
          <div className={styles.phoneCard}>
            <div className={styles.topBox}>
              <p className={styles.name}>Fabio dos santos </p>
              <div className={styles.options}>
                <a href="">Editar</a>
                <a href="">Excluir</a>
              </div>
            </div>
            <div className={styles.moreInfo}>
              <p>fabiojunik@gmail.com</p>
              <p>994305673</p>
              <p>Uma pessoa imortal</p>  
            </div>
          </div>
        </div>          
      </main>
  </>
)}

export default Home
